language: node_js

node_js:
  - "lts/*"

before_script:
  - npm run test-ts-decls
  - npm install

script:
  - npm run test-browser-ci
  - npm run test-browser-e2e-ci
  - npm run test-browser-offline
  - npm run test-browser-destroy
  - npm run test-browser-errors
  - npm run test-node | grep -e "# Summary" -e "fail: [^0]"
  - npm run test-node-e2e
  - npm run test-node-redis
  - npm run test-node-offline
  - npm run test-node-destroy
  - npm run test-node-errors
  - npm run lint
  - npm run rebuild
